/* PRK COMPUTER CENTER - PREMIUM SCRIPT */
window.addEventListener("scroll",function(){const header=document.querySelector("header");if(!header)return;if(window.scrollY>50){header.style.background="#00142e";header.style.boxShadow="0 5px 20px rgba(0,0,0,0.2)"}else{header.style.background="transparent";header.style.boxShadow="none"}});
const menuBtn=document.querySelector(".menu-btn"),nav=document.querySelector("nav");if(menuBtn)menuBtn.addEventListener("click",()=>nav&&nav.classList.toggle("active"));
const cards=document.querySelectorAll(".card");window.addEventListener("scroll",revealCards);function revealCards(){const t=window.innerHeight/1.2;cards.forEach(c=>{if(c.getBoundingClientRect().top<t){c.style.opacity="1";c.style.transform="translateY(0)"}})}cards.forEach(c=>{c.style.opacity="0";c.style.transform="translateY(50px)";c.style.transition=".6s ease"});
const counters=document.querySelectorAll(".counter");counters.forEach(counter=>{counter.innerText="0";const update=()=>{const target=+counter.getAttribute("data-target"),count=+counter.innerText,inc=target/100;if(count<target){counter.innerText=`${Math.ceil(count+inc)}`;setTimeout(update,20)}else counter.innerText=target};update()});
const typingText=document.querySelector(".typing-text");if(typingText){const arr=["Government Services","Online Form Filling","Computer Courses","CSC Services","Digital Solutions"];let ti=0,ci=0;function type(){if(ci<arr[ti].length){typingText.textContent+=arr[ti].charAt(ci++);setTimeout(type,100)}else setTimeout(erase,2000)}function erase(){if(ci>0){typingText.textContent=arr[ti].substring(0,--ci);setTimeout(erase,50)}else{ti=(ti+1)%arr.length;setTimeout(type,500)}}type()}
const buttons=document.querySelectorAll(".btn");buttons.forEach(b=>b.addEventListener("click",function(e){const r=document.createElement("span");r.style.left=`${e.clientX-e.target.offsetLeft}px`;r.style.top=`${e.clientY-e.target.offsetTop}px`;r.classList.add("ripple");this.appendChild(r);setTimeout(()=>r.remove(),600)}));
window.addEventListener("load",()=>{const l=document.querySelector(".loader");if(l){l.style.opacity="0";setTimeout(()=>l.style.display="none",500)}});
const topBtn=document.querySelector(".top-btn");window.addEventListener("scroll",()=>{if(topBtn)topBtn.style.display=window.scrollY>300?"flex":"none"});if(topBtn)topBtn.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
const sections=document.querySelectorAll("section"),navLinks=document.querySelectorAll("nav a");window.addEventListener("scroll",()=>{let current="";sections.forEach(s=>{if(scrollY>=s.offsetTop-200)current=s.getAttribute("id")});navLinks.forEach(l=>{l.classList.remove("active");if(l.getAttribute("href")&&l.getAttribute("href").includes(current))l.classList.add("active")})});
const galleryImages=document.querySelectorAll(".gallery-item img");galleryImages.forEach(img=>{img.addEventListener("mouseover",()=>{img.style.transform="scale(1.08)";img.style.transition=".5s"});img.addEventListener("mouseout",()=>img.style.transform="scale(1)")});
setTimeout(()=>{const n=document.createElement("div");n.innerHTML=`<div style="position:fixed;bottom:20px;left:20px;background:#0077ff;color:white;padding:18px 25px;border-radius:15px;box-shadow:0 10px 25px rgba(0,0,0,.2);z-index:9999;font-weight:600">🎉 Welcome to PRK Computer Center</div>`;document.body.appendChild(n);setTimeout(()=>n.remove(),5000)},2000);

/* CUSTOMER STATUS CHECKER */
(function(){if(location.pathname.endsWith("status.html"))return;const menu=document.querySelector(".menu");if(menu&&!menu.querySelector('a[href="status.html"]')){const a=document.createElement("a");a.href="status.html";a.textContent="काम का Status";a.style.color="#0866d8";a.style.fontWeight="900";menu.appendChild(a)}const actions=document.querySelector(".actions");if(actions&&!document.querySelector(".status-quick-btn")){const a=document.createElement("a");a.href="status.html";a.className="action status-quick-btn";a.textContent="🔎 काम का Status Check करें";actions.appendChild(a)}})();